create table shipwreck (
	id bigint generated by default as identity,
	condition varchar(255),
	depth integer,
	description varchar(255),
	latitude double,
	longitude double,
	name varchar(255),
	year_discovered integer,
	primary key (id))